modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/example/issueTracker"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/example/repo"
logoFile="logo.png"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.factorycore]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.factorycore]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.factorycore]]
modId="ghostlib"
type="required"
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"
